SYS-1651: fixing configs for nexus server
rhythmictech/terraform-aws-nexus pull request #22
Opened 2022-07-29 13:35 UTC by jjduverge

2022-08-10 13:42 UTC, sblack4 requested changes

2022-08-10 13:42 UTC, sblack4 commented on main.tf
> +    volume_type = var.root_volume_type
you should delete the old var for this, `var.asg_root_volume_type`

2022-08-24 19:57 UTC, sblack4 approved these changes

2022-08-24 20:04 UTC, cdaniluk requested changes

2022-08-24 20:04 UTC, cdaniluk commented on variables.tf
> +  default     = null
put in a default of 8 here since that's what the old default was. otherwise it will break things for people

2022-08-24 20:04 UTC, cdaniluk commented on variables.tf
> +  default     = "gp2"
make this gp3 since the old volume type was gp3

2022-08-24 20:10 UTC, cdaniluk approved these changes

2022-08-24 20:11 UTC, merged